name: Hello

on:
  push:
    branches: [main]

jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: print message
        run: echo "Hello from GitHub"

      - name: Print date and time
        run: date

      - name: print branch name
        run: echo "branch name:" {{ github.ref_name }}

        
        
    
